# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at https://dart.dev/lints.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    # avoid_print: false  # Uncomment to disable the `avoid_print` rule
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule
    
    # Disable stricter lints for better performance
    avoid_print: false
    cascade_invocations: false
    omit_local_variable_types: false
    prefer_double_quotes: false
    sized_box_for_whitespace: false
    use_key_in_widget_constructors: false
    
    # Additional documentation and style lints (safe to disable)
    public_member_api_docs: false
    comment_references: false
    require_trailing_commas: false
    lines_longer_than_80_chars: false
    leading_newlines_in_multiline_strings: false
    unnecessary_await_in_return: false
    unnecessary_lambdas: false
    unnecessary_parenthesis: false
    unnecessary_statements: false
    unnecessary_string_escapes: false
    unnecessary_string_interpolations: false
    unnecessary_to_list_in_spreads: false
    avoid_bool_literals_in_conditional_expressions: false
    avoid_catching_errors: false
    avoid_double_and_int_checks: false
    avoid_equals_and_hash_code_on_mutable_classes: false
    avoid_field_initializers_in_const_classes: false
    avoid_function_literals_in_foreach_calls: false
    avoid_init_to_null: false
    avoid_multiple_declarations_per_line: false
    avoid_null_checks_in_equality_operators: false
    avoid_positional_boolean_parameters: false
    avoid_private_typedef_functions: false
    avoid_returning_null_for_void: false
    avoid_returning_this: false
    avoid_setters_without_getters: false
    avoid_shadowing_type_parameters: false
    avoid_slow_async_io: false
    avoid_types_as_parameter_names: false
    avoid_types_on_closure_parameters: false
    close_sinks: false
    literal_only_boolean_expressions: false
    no_leading_underscores_for_library_prefixes: false
    noop_primitive_operations: false
    null_closures: false
    only_throw_errors: false
    parameter_assignments: false
    prefer_asserts_in_initializer_lists: false
    prefer_asserts_with_message: false
    prefer_collection_literals: false
    prefer_conditional_assignment: false
    prefer_const_constructors: false
    prefer_const_constructors_in_immutables: false
    prefer_const_declarations: false
    prefer_const_literals_to_create_immutables: false
    prefer_constructors_over_static_methods: false
    prefer_contains: false
    prefer_expression_function_bodies: false
    prefer_final_fields: false
    prefer_final_in_for_each: false
    prefer_final_locals: false
    prefer_for_elements_to_map_fromIterable: false
    prefer_foreach: false
    prefer_function_declarations_over_variables: false
    prefer_generic_function_type_aliases: false
    prefer_if_elements_to_conditional_expressions: false
    prefer_initializing_formals: false
    prefer_inlined_adds: false
    prefer_int_literals: false
    prefer_interpolation_to_compose_strings: false
    prefer_is_empty: false
    prefer_is_not_empty: false
    prefer_is_not_operator: false
    prefer_iterable_whereType: false
    prefer_mixin: false
    prefer_null_aware_operators: false
    prefer_relative_imports: false
    prefer_single_quotes: false
    provide_deprecation_message: false
    sort_child_properties_last: false
    sort_constructors_first: false
    sort_pub_dependencies: false
    sort_unnamed_constructors_first: false
    tighten_type_of_initializing_formals: false
    type_init_formals: false
    unnecessary_brace_in_string_interps: false
    unnecessary_const: false
    unnecessary_constructor_name: false
    unnecessary_getters_setters: false
    unnecessary_null_aware_assignments: false
    unnecessary_null_in_if_null_operators: false
    unnecessary_nullable_for_final_variable_declarations: false
    unnecessary_overrides: false
    unnecessary_this: false
    use_build_context_synchronously: false
    use_full_hex_values_for_flutter_colors: false
    use_function_type_syntax_for_parameters: false
    use_is_even_rather_than_modulo: false
    use_late_for_private_fields_and_variables: false
    use_rethrow_when_possible: false
    use_string_buffers: false
    use_test_throws_matchers: false
    void_checks: false

# Exclude third-party package examples/tests from project analysis
analyzer:
  exclude:
    - packages/**

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
