// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQoc8VxLwI3SGGIF7TYG8YHYXBG6NPVnk',
    appId: '1:728090004674:web:95f825b45bc3f5152c7f5b',
    messagingSenderId: '728090004674',
    projectId: 'bus-fleet-management',
    authDomain: 'bus-fleet-management.firebaseapp.com',
    databaseURL: 'https://bus-fleet-management-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bus-fleet-management.firebasestorage.app',
    measurementId: 'G-HPKSD0GSBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJul1hm3_X3dRJNKml1UTM5IKOAVMnsXY',
    appId: '1:728090004674:android:38661e0e2208c98a2c7f5b',
    messagingSenderId: '728090004674',
    projectId: 'bus-fleet-management',
    databaseURL: 'https://bus-fleet-management-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bus-fleet-management.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQoc8VxLwI3SGGIF7TYG8YHYXBG6NPVnk',
    appId: '1:728090004674:web:9f09334d86eb99282c7f5b',
    messagingSenderId: '728090004674',
    projectId: 'bus-fleet-management',
    authDomain: 'bus-fleet-management.firebaseapp.com',
    databaseURL: 'https://bus-fleet-management-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bus-fleet-management.firebasestorage.app',
    measurementId: 'G-7YMBT2BD6M',
  );
}
